# Server configuration
server.port=8080

# Logging configuration
logging.file.name=${LOGGING_FILE_PATH:/app/logs/spring-app.log}
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %p - %c - %m%n
logging.level.root=INFO
logging.level.com.example.demo=INFO
logging.level.org.springframework=WARN

# Increase log output to demonstrate sidecar functionality
logging.level.org.springframework.web=DEBUG